import type { BlogPost } from '../types'

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'The Ultimate Guide to Balayage: Everything You Need to Know',
    slug: 'ultimate-guide-to-balayage',
    image: '/images/blog/b1.jpg',
    excerpt: 'Discover the art of dimension, maintenance and face-flattering shades of the world\'s most requested color technique.',
    category: 'Hair Care',
    author: 'Aurora Vance',
    tags: ['balayage', 'color', 'trends'],
    readTime: 6,
    publishedAt: '2026-07-20',
    featured: true,
    content: 'Balayage translates from the French word meaning "to sweep" — and that is precisely the artistry behind this beloved colour technique. Instead of painting colour from root to tip, the stylist sweeps colour onto the surface of the hair in freehand strokes.\n\nThe result is a soft, sun-kissed gradient that grows out beautifully and requires far less maintenance than traditional all-over colour.\n\nChoosing the right shade is essential. Warm caramel suits deeper skin tones, cool ash tones flatter fair complexions, and rich bronze adds dimension to brunette hair.\n\nOur master colourists begin with a full consultation to map the placement, then blend multiple tones for depth. Every balayage is bespoke — no two heads are ever the same.\n\nTo prolong your colour, we recommend our ammonia-free aftercare range and visiting once every three to four months. Your stylist can show you exactly how to care for the tone at home.',
  },
  {
    id: 'b2',
    title: '10 Skincare Rituals for Naturally Glowing Skin',
    slug: '10-skincare-rituals-for-glowing-skin',
    image: '/images/blog/b2.jpg',
    excerpt: 'Unlock a luminous complexion with our therapist-approved daily rituals anyone can master at home.',
    category: 'Skin Care',
    author: 'Sofia Lindqvist',
    tags: ['skincare', 'glow', 'rituals'],
    readTime: 5,
    publishedAt: '2026-07-12',
    content: 'A glowing complexion is rarely the result of one single product — it is a daily ritual, consistently performed.\n\nStart with a gentle double cleanse. The first removes makeup and pollutants; the second treats the skin. Use lukewarm water, never hot, to avoid stripping your natural barrier.\n\nFollow with a hydrating essence or toner applied with light, upward strokes. Then lock in moisture while the skin is still damp — this is when hyaluronic acid works best.\n\nAt night, apply a facial oil or night cream suited to your skin type, and never skip SPF during the day.\n\nOnce a week, exfoliate gently and finish with a nourishing mask. Our therapists recommend booking a professional facial once a month for deeper results.',
  },
  {
    id: 'b3',
    title: 'Keratin vs Smoothening: Which Treatment Is Right for You?',
    slug: 'keratin-vs-smoothening',
    image: '/images/blog/b3.jpg',
    excerpt: 'We break down the differences, benefits and longevity of each transformative service so you choose with confidence.',
    category: 'Hair Care',
    author: 'Marco Reyes',
    tags: ['keratin', 'smoothening', 'hair'],
    readTime: 7,
    publishedAt: '2026-06-28',
    content: 'Keratin and smoothing treatments both aim for sleeker hair, but they work in very different ways.\n\nKeratin treatments infuse the hair shaft with protein to rebuild damage from within, leaving hair stronger, glossier and more resistant to humidity. They are ideal for chemically treated or porous hair.\n\nSmoothening treatments coat the cuticle to relax the natural texture, giving a softer, straighter finish with less frizz. They suit most hair types and offer a more natural look.\n\nConsider your lifestyle: if you swim often or live in a humid climate, keratin offers the longest-lasting resilience. If you prefer subtle movement and softness, smoothing may be the better choice.\n\nEither way, our experts will assess your hair during a consultation and recommend the treatment best matched to your goals.',
  },
  {
    id: 'b4',
    title: 'Bridal Hair & Makeup Trends for This Wedding Season',
    slug: 'bridal-hair-makeup-trends',
    image: '/images/blog/b4.jpg',
    excerpt: 'Soft glam, slick buns and luminous skin — the season\'s most requested bridal looks revealed.',
    category: 'Trends',
    author: 'Elena Moreau',
    tags: ['bridal', 'wedding', 'trends'],
    readTime: 4,
    publishedAt: '2026-06-15',
    content: 'This season, bridal beauty is all about looking radiantly, effortlessly you.\n\nSoft glam remains the most requested look — glowing skin, feather-light lashes and a subtle metallic shimmer. It photographs beautifully and feels timeless.\n\nFor hair, sculpted buns and low chignons adorned with pearls or delicate florals are in high demand. Loose, face-framing waves offer a romantic, modern alternative.\n\nYour skin will glow from within with a month of pre-wedding facials, and we always schedule a trial at least four weeks before the big day.\n\nBook your bridal consultation early — our calendar fills quickly during wedding season.',
  },
]