import type { Stylist, Testimonial } from '../types'

export const STYLISTS: Stylist[] = [
  {
    id: 'aurora',
    name: 'Aurora Vance',
    role: 'Founder & Creative Director',
    image: '/images/stylists/aurora.jpg',
    experience: 15,
    specialization: ['Signature Cuts', 'Color Artistry', 'Editorial'],
    awards: ['International Hairdressers Award 2023', 'Best Colorist — West Coast'],
    socials: { instagram: '#', facebook: '#', twitter: '#' },
    bio: 'Award-winning visionary behind Maison Aurelle, celebrating 15 years of precision artistry.',
    featured: true,
  },
  {
    id: 'elena',
    name: 'Elena Moreau',
    role: 'Bridal Makeup Artist',
    image: '/images/stylists/elena.jpg',
    experience: 9,
    specialization: ['Bridal Makeup', 'HD Artistry', 'Photography'],
    awards: ['Bridal Stylist of the Year 2024'],
    socials: { instagram: '#', facebook: '#' },
    bio: 'Specialist in picture-perfect bridal looks that last all day and glow all night.',
  },
  {
    id: 'marco',
    name: 'Marco Reyes',
    role: 'Keratin & Smoothing Expert',
    image: '/images/stylists/marco.jpg',
    experience: 11,
    specialization: ['Keratin', 'Smoothening', 'Straightening'],
    awards: ['Keratin Master 2022'],
    socials: { instagram: '#', twitter: '#' },
    bio: 'Transformative hair restructuring with a reputation for mirror-shine results.',
  },
  {
    id: 'sofia',
    name: 'Sofia Lindqvist',
    role: 'Spa & Wellness Therapist',
    image: '/images/stylists/sofia.jpg',
    experience: 7,
    specialization: ['Head Massage', 'Therapy Massage', 'Scalp Rituals'],
    awards: [],
    socials: { instagram: '#', facebook: '#', twitter: '#' },
    bio: 'A healing touch that blends deep relaxation with therapeutic precision.',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Isabella Carter',
    rating: 5,
    service: 'Bridal Makeup',
    content: 'Aurora and her team made my wedding day unforgettable. The makeup lasted 14 hours and looked flawless in every photograph. An extraordinary experience.',
  },
  {
    id: 't2',
    name: 'James Whitfield',
    rating: 5,
    service: 'Signature Haircut',
    content: 'The most refined salon I have ever visited. Attentive staff, immaculate interior, and a haircut that has people asking where I go.',
  },
  {
    id: 't3',
    name: 'Amelia Nguyen',
    rating: 5,
    service: 'Keratin Treatment',
    content: 'My hair has never felt healthier. Marco is an absolute artist with keratin. Worth every penny for the confidence it gives me.',
  },
  {
    id: 't4',
    name: 'Victoria Adams',
    rating: 4,
    service: 'Hair Coloring',
    content: 'Incredible balayage work with rich, dimensional color. Booking is easy and the atmosphere is pure luxury.',
  },
  {
    id: 't5',
    name: 'Lucas Ferrera',
    rating: 5,
    service: 'Royal Shave',
    content: 'A traditional hot-towel shave done to perfection. Quiet, relaxed and genuinely pampering. This is grooming elevated.',
  },
  {
    id: 't6',
    name: "Charlotte O'Shea",
    rating: 5,
    service: 'Luxury Facial',
    content: 'My skin is glowing! The facial was deeply relaxing and the results were visible immediately. A true sanctuary.',
  },
]